name: 'Notify release to Slack'
description: 'Get release message and send to Slack'
inputs:
  slackWebhookUrl:
    description: 'Slack incomming webhook url'
    required: true
  releaseMessage:
    description: 'Release message'
    required: false
outputs:
  response:
    description: 'Response from Slack'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'bell'
  color: 'blue'
